services:
  sgrup13: # Aplicació
    image: igrup13
    build: .
    expose:
      - "80"
    volumes:
      - vgrup13:/var/www/html
    environment:
      - HOST_NAME=ops_grup13
    networks:
      - xgrup13

  sDc: # Distribuidor de carrega
    image: nginx:latest
    container_name: cnginx
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - sgrup13
    ports:
      - "80:8000"
    networks:
      - xgrup13

volumes:
  vgrup13:
    name: volum13

networks:
  xgrup13:
    name: grup13
    driver: bridge
